name: ReadyShips
favicon: null
layout_spectrum: 0.17850476666353643
typography_spectrum: 0.45874965423718095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020006'
    - '#1d44d9'
    - '#ff2335'
    - '#4ba4fa'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
